### ISSUE TITLE
Problem trying to create folders

### ISSUE THREAD

**Issue by osome** [simonmoreau/bimsyncManager#6]
Hi, 

I'm trying to create folders in an existing project, but the creating screen stays endless and nothing is created.

I'm attaching the sample json.
[FolderStructure.json.txt](https://github.com/simonmoreau/bimsyncManager/files/3428005/FolderStructure.json.txt)

**Comment by simonmoreau** [comment]
Hi,

I looked into the sample you give me and found an issue in the json: just after "folders":, you need to add square brackets [] before defining your folder. This allows the creation of multiple folders. Here is the corrected sample:

`[
	{
		"folders": [
			{
				"name": "03_VIDEOWALL",
				"folders": [
					{
						"name": "01_PLANOS"
					},
					{
						"name": "02_DOC DALI"
					},
					{
						"name": "03_PRODUCCION SENALES"
					},
					{
						"name": "04_DOC GRAFICA"
					}
				]
			}
		]
	}
]`
